name: Morning Briefing

on:
  schedule:
    - cron: '0 7 * * *'  # 7 AM UTC daily (8 AM BST / 7 AM GMT)
  workflow_dispatch:      # Manual trigger

jobs:
  generate-briefing:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London  # Critical for correct timezone handling
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Generate morning briefing
        run: node dist/bundle/index.js
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dailybriefs/*.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add morning briefing for $(date -d 'TZ="Europe/London"' +'%Y-%m-%d')"
            git push
          fi